{
	"repos": [
		{
			"repo": "local",
			"hooks": [
				{
					"id": "ghdl-fmt",
					"name": "GHDL Format",
					"entry": "ghdl fmt",
					"language": "system",
					"files": "\\.(vhdl|vhd)$"
				}
			]
		}
	]
}
