# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: ghdl-fmt
        name: Format VHDL files with GHDL
        entry: bash -c 'find . -name "*.vhd" -print0 | xargs -0 -n1 ghdl --format'
        language: system
        files: \.vhd$
