[project]
name = "cpre488-mp1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.9.20"
dependencies = [
    "hdl-checker>=0.7.4",
    "pre-commit>=4.1.0",
]

